
// auto-generated by generate.mts

export const PRECALCULATED_COUNTRY_TIMEZONE_MAP = {
  "AD": "Europe/Andorra",
  "AE": "Asia/Dubai",
  "AF": "Asia/Kabul",
  "AG": "America/Antigua",
  "AI": "America/Anguilla",
  "AL": "Europe/Tirane",
  "AM": "Asia/Yerevan",
  "AO": "Africa/Luanda",
  "AQ": "Antarctica/McMurdo",
  "AR": "America/Argentina/Buenos_Aires",
  "AS": "Pacific/Pago_Pago",
  "AT": "Europe/Vienna",
  "AU": "Australia/Lord_Howe",
  "AW": "America/Aruba",
  "AX": "Europe/Mariehamn",
  "AZ": "Asia/Baku",
  "BA": "Europe/Sarajevo",
  "BB": "America/Barbados",
  "BD": "Asia/Dhaka",
  "BE": "Europe/Brussels",
  "BF": "Africa/Ouagadougou",
  "BG": "Europe/Sofia",
  "BH": "Asia/Bahrain",
  "BI": "Africa/Bujumbura",
  "BJ": "Africa/Porto-Novo",
  "BL": "America/St_Barthelemy",
  "BM": "Atlantic/Bermuda",
  "BN": "Asia/Brunei",
  "BO": "America/La_Paz",
  "BQ": "America/Kralendijk",
  "BR": "America/Noronha",
  "BS": "America/Nassau",
  "BT": "Asia/Thimphu",
  "BW": "Africa/Gaborone",
  "BY": "Europe/Minsk",
  "BZ": "America/Belize",
  "CA": "America/St_Johns",
  "CC": "Indian/Cocos",
  "CD": "Africa/Lubumbashi",
  "CF": "Africa/Bangui",
  "CG": "Africa/Brazzaville",
  "CH": "Europe/Zurich",
  "CI": "Africa/Abidjan",
  "CK": "Pacific/Rarotonga",
  "CL": "America/Santiago",
  "CM": "Africa/Douala",
  "CN": "Asia/Shanghai",
  "CO": "America/Bogota",
  "CR": "America/Costa_Rica",
  "CU": "America/Havana",
  "CV": "Atlantic/Cape_Verde",
  "CW": "America/Curacao",
  "CX": "Indian/Christmas",
  "CY": "Asia/Nicosia",
  "CZ": "Europe/Prague",
  "DE": "Europe/Berlin",
  "DJ": "Africa/Djibouti",
  "DK": "Europe/Copenhagen",
  "DM": "America/Dominica",
  "DO": "America/Santo_Domingo",
  "DZ": "Africa/Algiers",
  "EC": "America/Guayaquil",
  "EE": "Europe/Tallinn",
  "EG": "Africa/Cairo",
  "EH": "Africa/El_Aaiun",
  "ER": "Africa/Asmara",
  "ES": "Europe/Madrid",
  "ET": "Africa/Addis_Ababa",
  "FI": "Europe/Helsinki",
  "FJ": "Pacific/Fiji",
  "FK": "Atlantic/Stanley",
  "FM": "Pacific/Kosrae",
  "FO": "Atlantic/Faroe",
  "FR": "Europe/Paris",
  "GA": "Africa/Libreville",
  "GB": "Europe/London",
  "GD": "America/Grenada",
  "GE": "Asia/Tbilisi",
  "GF": "America/Cayenne",
  "GG": "Europe/Guernsey",
  "GH": "Africa/Accra",
  "GI": "Europe/Gibraltar",
  "GL": "America/Danmarkshavn",
  "GM": "Africa/Banjul",
  "GN": "Africa/Conakry",
  "GP": "America/Guadeloupe",
  "GQ": "Africa/Malabo",
  "GR": "Europe/Athens",
  "GS": "Atlantic/South_Georgia",
  "GT": "America/Guatemala",
  "GU": "Pacific/Guam",
  "GW": "Africa/Bissau",
  "GY": "America/Guyana",
  "HK": "Asia/Hong_Kong",
  "HN": "America/Tegucigalpa",
  "HR": "Europe/Zagreb",
  "HT": "America/Port-au-Prince",
  "HU": "Europe/Budapest",
  "ID": "Asia/Jayapura",
  "IE": "Europe/Dublin",
  "IL": "Asia/Jerusalem",
  "IM": "Europe/Isle_of_Man",
  "IN": "Asia/Kolkata",
  "IO": "Indian/Chagos",
  "IQ": "Asia/Baghdad",
  "IR": "Asia/Tehran",
  "IS": "Atlantic/Reykjavik",
  "IT": "Europe/Rome",
  "JE": "Europe/Jersey",
  "JM": "America/Jamaica",
  "JO": "Asia/Amman",
  "JP": "Asia/Tokyo",
  "KE": "Africa/Nairobi",
  "KG": "Asia/Bishkek",
  "KH": "Asia/Phnom_Penh",
  "KI": "Pacific/Kiritimati",
  "KM": "Indian/Comoro",
  "KN": "America/St_Kitts",
  "KP": "Asia/Pyongyang",
  "KR": "Asia/Seoul",
  "KW": "Asia/Kuwait",
  "KY": "America/Cayman",
  "KZ": "Asia/Almaty",
  "LA": "Asia/Vientiane",
  "LB": "Asia/Beirut",
  "LC": "America/St_Lucia",
  "LI": "Europe/Vaduz",
  "LK": "Asia/Colombo",
  "LR": "Africa/Monrovia",
  "LS": "Africa/Maseru",
  "LT": "Europe/Vilnius",
  "LU": "Europe/Luxembourg",
  "LV": "Europe/Riga",
  "LY": "Africa/Tripoli",
  "MA": "Africa/Casablanca",
  "MC": "Europe/Monaco",
  "MD": "Europe/Chisinau",
  "ME": "Europe/Podgorica",
  "MF": "America/Marigot",
  "MG": "Indian/Antananarivo",
  "MH": "Pacific/Majuro",
  "MK": "Europe/Skopje",
  "ML": "Africa/Bamako",
  "MM": "Asia/Yangon",
  "MN": "Asia/Ulaanbaatar",
  "MO": "Asia/Macau",
  "MP": "Pacific/Saipan",
  "MQ": "America/Martinique",
  "MR": "Africa/Nouakchott",
  "MS": "America/Montserrat",
  "MT": "Europe/Malta",
  "MU": "Indian/Mauritius",
  "MV": "Indian/Maldives",
  "MW": "Africa/Blantyre",
  "MX": "America/Cancun",
  "MY": "Asia/Kuala_Lumpur",
  "MZ": "Africa/Maputo",
  "NA": "Africa/Windhoek",
  "NC": "Pacific/Noumea",
  "NE": "Africa/Niamey",
  "NF": "Pacific/Norfolk",
  "NG": "Africa/Lagos",
  "NI": "America/Managua",
  "NL": "Europe/Amsterdam",
  "NO": "Europe/Oslo",
  "NP": "Asia/Kathmandu",
  "NR": "Pacific/Nauru",
  "NU": "Pacific/Niue",
  "NZ": "Pacific/Chatham",
  "OM": "Asia/Muscat",
  "PA": "America/Panama",
  "PE": "America/Lima",
  "PF": "Pacific/Gambier",
  "PG": "Pacific/Bougainville",
  "PH": "Asia/Manila",
  "PK": "Asia/Karachi",
  "PL": "Europe/Warsaw",
  "PM": "America/Miquelon",
  "PN": "Pacific/Pitcairn",
  "PR": "America/Puerto_Rico",
  "PS": "Asia/Hebron",
  "PT": "Europe/Lisbon",
  "PW": "Pacific/Palau",
  "PY": "America/Asuncion",
  "QA": "Asia/Qatar",
  "RE": "Indian/Reunion",
  "RO": "Europe/Bucharest",
  "RS": "Europe/Belgrade",
  "RU": "Asia/Kamchatka",
  "RW": "Africa/Kigali",
  "SA": "Asia/Riyadh",
  "SB": "Pacific/Guadalcanal",
  "SC": "Indian/Mahe",
  "SD": "Africa/Khartoum",
  "SE": "Europe/Stockholm",
  "SG": "Asia/Singapore",
  "SH": "Atlantic/St_Helena",
  "SI": "Europe/Ljubljana",
  "SJ": "Arctic/Longyearbyen",
  "SK": "Europe/Bratislava",
  "SL": "Africa/Freetown",
  "SM": "Europe/San_Marino",
  "SN": "Africa/Dakar",
  "SO": "Africa/Mogadishu",
  "SR": "America/Paramaribo",
  "SS": "Africa/Juba",
  "ST": "Africa/Sao_Tome",
  "SV": "America/El_Salvador",
  "SX": "America/Lower_Princes",
  "SY": "Asia/Damascus",
  "SZ": "Africa/Mbabane",
  "TC": "America/Grand_Turk",
  "TD": "Africa/Ndjamena",
  "TF": "Indian/Kerguelen",
  "TG": "Africa/Lome",
  "TH": "Asia/Bangkok",
  "TJ": "Asia/Dushanbe",
  "TK": "Pacific/Fakaofo",
  "TL": "Asia/Dili",
  "TM": "Asia/Ashgabat",
  "TN": "Africa/Tunis",
  "TO": "Pacific/Tongatapu",
  "TR": "Europe/Istanbul",
  "TT": "America/Port_of_Spain",
  "TV": "Pacific/Funafuti",
  "TW": "Asia/Taipei",
  "TZ": "Africa/Dar_es_Salaam",
  "UA": "Europe/Simferopol",
  "UG": "Africa/Kampala",
  "UM": "Pacific/Wake",
  "US": "America/New_York",
  "UY": "America/Montevideo",
  "UZ": "Asia/Tashkent",
  "VA": "Europe/Vatican",
  "VC": "America/St_Vincent",
  "VE": "America/Caracas",
  "VG": "America/Tortola",
  "VI": "America/St_Thomas",
  "VN": "Asia/Ho_Chi_Minh",
  "VU": "Pacific/Efate",
  "WF": "Pacific/Wallis",
  "WS": "Pacific/Apia",
  "YE": "Asia/Aden",
  "YT": "Indian/Mayotte",
  "ZA": "Africa/Johannesburg",
  "ZM": "Africa/Lusaka",
  "ZW": "Africa/Harare"
} as const;

export const PRECALCULATED_DISPLAYS = [
  {
    "x": 0,
    "d": 86400,
    "p": [
      {
        "c": "p00",
        "i": 2,
        "k": [
          72000000,
          72000100,
          86400000,
          86400100
        ]
      },
      {
        "c": "p01",
        "i": 0,
        "k": [
          36000000,
          36000100,
          86400000,
          86400100
        ]
      },
      {
        "c": "p02",
        "i": 0,
        "k": [
          36000000,
          36000100,
          72000000,
          72000100
        ]
      },
      {
        "c": "p03",
        "i": 0,
        "k": [
          36000000,
          36000100,
          72000000,
          72000100
        ]
      },
      {
        "c": "p04",
        "i": 0,
        "k": [
          72000000,
          72000100,
          86400000,
          86400100
        ]
      },
      {
        "c": "p05",
        "i": 0,
        "k": []
      },
      {
        "c": "p06",
        "i": 0,
        "k": [
          36000000,
          36000100,
          72000000,
          72000100
        ]
      }
    ]
  },
  {
    "x": 140,
    "d": 86400,
    "p": [
      {
        "c": "p10",
        "i": 2,
        "k": [
          7200000,
          7200100,
          25200000,
          25200100,
          28800000,
          28800100,
          36000000,
          36000100,
          43200000,
          43200100,
          61200000,
          61200100,
          64800000,
          64800100,
          72000000,
          72000100,
          79200000,
          79200100,
          86400000,
          86400100
        ]
      },
      {
        "c": "p11",
        "i": 0,
        "k": [
          3600000,
          3600100,
          14400000,
          14400100,
          25200000,
          25200100,
          28800000,
          28800100,
          39600000,
          39600100,
          50400000,
          50400100,
          61200000,
          61200100,
          64800000,
          64800100,
          75600000,
          75600100,
          86400000,
          86400100
        ]
      },
      {
        "c": "p12",
        "i": 0,
        "k": [
          3600000,
          3600100,
          7200000,
          7200100,
          10800000,
          10800100,
          21600000,
          21600100,
          25200000,
          25200100,
          28800000,
          28800100,
          32400000,
          32400100,
          36000000,
          36000100,
          39600000,
          39600100,
          43200000,
          43200100,
          46800000,
          46800100,
          57600000,
          57600100,
          61200000,
          61200100,
          64800000,
          64800100,
          68400000,
          68400100,
          72000000,
          72000100,
          75600000,
          75600100,
          79200000,
          79200100,
          82800000,
          82800100,
          86400000,
          86400100
        ]
      },
      {
        "c": "p13",
        "i": 0,
        "k": [
          3600000,
          3600100,
          7200000,
          7200100,
          14400000,
          14400100,
          18000000,
          18000100,
          25200000,
          25200100,
          28800000,
          28800100,
          39600000,
          39600100,
          43200000,
          43200100,
          50400000,
          50400100,
          54000000,
          54000100,
          61200000,
          61200100,
          64800000,
          64800100,
          75600000,
          75600100,
          79200000,
          79200100
        ]
      },
      {
        "c": "p14",
        "i": 0,
        "k": [
          7200000,
          7200100,
          10800000,
          10800100,
          43200000,
          43200100,
          46800000,
          46800100,
          79200000,
          79200100,
          82800000,
          82800100
        ]
      },
      {
        "c": "p15",
        "i": 0,
        "k": [
          18000000,
          18000100,
          25200000,
          25200100,
          54000000,
          54000100,
          61200000,
          61200100
        ]
      },
      {
        "c": "p16",
        "i": 0,
        "k": [
          3600000,
          3600100,
          7200000,
          7200100,
          14400000,
          14400100,
          18000000,
          18000100,
          39600000,
          39600100,
          43200000,
          43200100,
          50400000,
          50400100,
          54000000,
          54000100,
          75600000,
          75600100,
          79200000,
          79200100
        ]
      }
    ]
  },
  {
    "x": 320,
    "d": 3600,
    "p": [
      {
        "c": "p30",
        "i": 2,
        "k": [
          1200000,
          1200100,
          3600000,
          3600100
        ]
      },
      {
        "c": "p31",
        "i": 0,
        "k": [
          600000,
          600100,
          2400000,
          2400100
        ]
      },
      {
        "c": "p32",
        "i": 0,
        "k": [
          600000,
          600100,
          1200000,
          1200100,
          1800000,
          1800100,
          3600000,
          3600100
        ]
      },
      {
        "c": "p33",
        "i": 0,
        "k": [
          600000,
          600100,
          1200000,
          1200100,
          2400000,
          2400100,
          3000000,
          3000100
        ]
      },
      {
        "c": "p34",
        "i": 0,
        "k": [
          1200000,
          1200100,
          1800000,
          1800100
        ]
      },
      {
        "c": "p35",
        "i": 0,
        "k": [
          3000000,
          3000100,
          3600000,
          3600100
        ]
      },
      {
        "c": "p36",
        "i": 0,
        "k": [
          600000,
          600100,
          1200000,
          1200100,
          2400000,
          2400100,
          3000000,
          3000100
        ]
      }
    ]
  },
  {
    "x": 460,
    "d": 600,
    "p": [
      {
        "c": "p40",
        "i": 2,
        "k": [
          120000,
          120100,
          420000,
          420100,
          480000,
          480100,
          600000,
          600100
        ]
      },
      {
        "c": "p41",
        "i": 0,
        "k": [
          60000,
          60100,
          240000,
          240100,
          420000,
          420100,
          480000,
          480100
        ]
      },
      {
        "c": "p42",
        "i": 0,
        "k": [
          60000,
          60100,
          120000,
          120100,
          180000,
          180100,
          360000,
          360100,
          420000,
          420100,
          480000,
          480100,
          540000,
          540100,
          600000,
          600100
        ]
      },
      {
        "c": "p43",
        "i": 0,
        "k": [
          60000,
          60100,
          120000,
          120100,
          240000,
          240100,
          300000,
          300100,
          420000,
          420100,
          480000,
          480100
        ]
      },
      {
        "c": "p44",
        "i": 0,
        "k": [
          120000,
          120100,
          180000,
          180100
        ]
      },
      {
        "c": "p45",
        "i": 0,
        "k": [
          300000,
          300100,
          420000,
          420100
        ]
      },
      {
        "c": "p46",
        "i": 0,
        "k": [
          60000,
          60100,
          120000,
          120100,
          240000,
          240100,
          300000,
          300100
        ]
      }
    ]
  },
  {
    "x": 640,
    "d": 60,
    "p": [
      {
        "c": "p60",
        "i": 2,
        "k": [
          20000,
          20100,
          60000,
          60100
        ]
      },
      {
        "c": "p61",
        "i": 0,
        "k": [
          10000,
          10100,
          40000,
          40100
        ]
      },
      {
        "c": "p62",
        "i": 0,
        "k": [
          10000,
          10100,
          20000,
          20100,
          30000,
          30100,
          60000,
          60100
        ]
      },
      {
        "c": "p63",
        "i": 0,
        "k": [
          10000,
          10100,
          20000,
          20100,
          40000,
          40100,
          50000,
          50100
        ]
      },
      {
        "c": "p64",
        "i": 0,
        "k": [
          20000,
          20100,
          30000,
          30100
        ]
      },
      {
        "c": "p65",
        "i": 0,
        "k": [
          50000,
          50100,
          60000,
          60100
        ]
      },
      {
        "c": "p66",
        "i": 0,
        "k": [
          10000,
          10100,
          20000,
          20100,
          40000,
          40100,
          50000,
          50100
        ]
      }
    ]
  },
  {
    "x": 780,
    "d": 10,
    "p": [
      {
        "c": "p70",
        "i": 2,
        "k": [
          2000,
          2100,
          7000,
          7100,
          8000,
          8100,
          10000,
          10100
        ]
      },
      {
        "c": "p71",
        "i": 0,
        "k": [
          1000,
          1100,
          4000,
          4100,
          7000,
          7100,
          8000,
          8100
        ]
      },
      {
        "c": "p72",
        "i": 0,
        "k": [
          1000,
          1100,
          2000,
          2100,
          3000,
          3100,
          6000,
          6100,
          7000,
          7100,
          8000,
          8100,
          9000,
          9100,
          10000,
          10100
        ]
      },
      {
        "c": "p73",
        "i": 0,
        "k": [
          1000,
          1100,
          2000,
          2100,
          4000,
          4100,
          5000,
          5100,
          7000,
          7100,
          8000,
          8100
        ]
      },
      {
        "c": "p74",
        "i": 0,
        "k": [
          2000,
          2100,
          3000,
          3100
        ]
      },
      {
        "c": "p75",
        "i": 0,
        "k": [
          5000,
          5100,
          7000,
          7100
        ]
      },
      {
        "c": "p76",
        "i": 0,
        "k": [
          1000,
          1100,
          2000,
          2100,
          4000,
          4100,
          5000,
          5100
        ]
      }
    ]
  }
] as const;

export function createSVG({style, extraContent, linkURL}: {style: string; extraContent: string; linkURL: string;}) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="-40 -10 920 200">
<style>
${style}.u { opacity: 0; display: none }
@media (prefers-color-scheme: dark) {
:root { color-scheme: dark }
}
</style>
<defs>
<path id="s0" d="M12,90L22,81L79,81L88,90L79,100L22,100Z" />
<path id="s1" d="M10,88L0,79L0,22L10,12L20,22L20,79Z" />
<path id="s2" d="M10,168L0,159L0,102L10,92L20,102L20,159Z" />
<path id="s3" d="M88,170L79,180L22,180L12,170L22,161L79,161Z" />
<path id="s4" d="M90,92L100,102L100,159L90,168L80,159L80,102Z" />
<path id="s5" d="M90,12L100,22L100,79L90,88L80,79L81,22Z" />
<path id="s6" d="M12,10L22,1L79,0L88,10L79,20L22,20Z" />
</defs>
<g transform="skewX(-12.5)" stroke="none" fill="#2871fc">
<g transform="translate(0, 0)">
<use href="#s0" class="p00" />
<use href="#s1" class="p01" />
<use href="#s2" class="p02" />
<use href="#s3" class="p03" />
<use href="#s4" class="p04" />
<use href="#s5" class="p05" />
<use href="#s6" class="p06" />
</g>
<g transform="translate(140, 0)">
<use href="#s0" class="p10" />
<use href="#s1" class="p11" />
<use href="#s2" class="p12" />
<use href="#s3" class="p13" />
<use href="#s4" class="p14" />
<use href="#s5" class="p15" />
<use href="#s6" class="p16" />
</g>
<g transform="translate(280, 0)">
<circle cx="0" cy="40" r="10" />
<circle cx="0" cy="140" r="10" />
</g>
<g transform="translate(320, 0)">
<use href="#s0" class="p30" />
<use href="#s1" class="p31" />
<use href="#s2" class="p32" />
<use href="#s3" class="p33" />
<use href="#s4" class="p34" />
<use href="#s5" class="p35" />
<use href="#s6" class="p36" />
</g>
<g transform="translate(460, 0)">
<use href="#s0" class="p40" />
<use href="#s1" class="p41" />
<use href="#s2" class="p42" />
<use href="#s3" class="p43" />
<use href="#s4" class="p44" />
<use href="#s5" class="p45" />
<use href="#s6" class="p46" />
</g>
<g transform="translate(600, 0)">
<circle cx="0" cy="40" r="10" />
<circle cx="0" cy="140" r="10" />
</g>
<g transform="translate(640, 0)">
<use href="#s0" class="p60" />
<use href="#s1" class="p61" />
<use href="#s2" class="p62" />
<use href="#s3" class="p63" />
<use href="#s4" class="p64" />
<use href="#s5" class="p65" />
<use href="#s6" class="p66" />
</g>
<g transform="translate(780, 0)">
<use href="#s0" class="p70" />
<use href="#s1" class="p71" />
<use href="#s2" class="p72" />
<use href="#s3" class="p73" />
<use href="#s4" class="p74" />
<use href="#s5" class="p75" />
<use href="#s6" class="p76" />
</g>
</g>
${extraContent}<g class="u">
<a href="${linkURL}">
<text x="860" y="235" stroke="none" fill="#2871fc" font-size="50" text-anchor="end" font-family="Verdana, Arial, Helvetica, sans-serif">Not working?</text>
</a>
</g>
</svg>
`;
}

